services:
    nats:
        image: nats:latest
        ports:
            - "4222:4222"

    mongo-auth:
        image: mongo:latest
        container_name: mongo-auth
        ports:
            - "27017:27017"
        volumes:
            - mongo_auth_data:/data/db

        mongo-express-auth:
            image: mongo-express:latest
            ports:
                - "8081:8081"
            environment:
                ME_CONFIG_MONGODB_SERVER: mongo-auth
                ME_CONFIG_BASICAUTH: false

    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: help
        ports:
            - 3307:3306 # portlocal:portducontainer
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db

volumes:
    db_data:
    mongo_auth_data:
