services:
    # -------------------------
    # EVENT BUS
    # -------------------------
    nats:
        image: nats:latest
        ports:
            - "4222:4222"

    # -------------------------
    # AUTH SERVICE
    # -------------------------
    ms-auth:
        image: ghcr.io/maximetavares/ms-auth:latest
        restart: always
        env_file:
            - .env
        environment:
            - NATS_URL=nats://nats:4222
        depends_on:
            - nats

    # -------------------------
    # GATEWAY
    # -------------------------
    gateway:
        image: ghcr.io/maximetavares/gateway:latest
        ports:
            - "3000:3000"
        restart: always
        env_file:
            - .env
        environment:
            - NATS_URL=nats://nats:4222
            - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
        depends_on:
            - nats

    # -------------------------
    # FRONT
    # -------------------------
    front:
        image: ghcr.io/maximetavares/front:latest
        ports:
            - "80:80"
        restart: always
