services:

  # -------------------------
  # EVENT BUS
  # -------------------------
  prod-nats:
    image: nats:latest
    restart: unless-stopped
    container_name: prod-nats
    networks:
      - nginx-prod

  # -------------------------
  # AUTH SERVICE
  # -------------------------
  prod-ms-auth:
    image: ghcr.io/maximetavares/ms-auth:${IMAGE_TAG}
    restart: unless-stopped
    container_name: prod-ms-auth
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    env_file:
      - .env

    depends_on:
      prod-nats:
        condition: service_started

    networks:
      - nginx-prod

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 10s

  # -------------------------
  # GATEWAY
  # -------------------------
  prod-gateway:
    image: ghcr.io/maximetavares/gateway:${IMAGE_TAG}
    restart: unless-stopped
    container_name: prod-gateway
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    env_file:
      - .env

    depends_on:
      prod-nats:
        condition: service_started

    networks:
      - nginx-prod

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 10s

  # -------------------------
  # FRONT
  # -------------------------
  prod-front:
    image: ghcr.io/maximetavares/front:prod
    restart: unless-stopped
    container_name: prod-front

    networks:
      - nginx-prod

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3

# -------------------------
# NETWORK
# -------------------------
networks:
  nginx-prod:
    external: true
    name: nginx-prod