services:
    # -------------------------
    # EVENT BUS
    # -------------------------
    nats:
        image: nats:latest
        container_name: nats-alt
        ports:
            - "4222:4222"

    # -------------------------
    # AUTH DB
    # -------------------------
    mongo-auth:
        image: mongo:latest
        container_name: mongo-auth
        ports:
            - "27017:27017"
        volumes:
            - mongo_auth_data:/data/db

    mongo-express-auth:
        image: mongo-express:latest
        container_name: mongo-express-auth
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo-auth
            ME_CONFIG_BASICAUTH: false
        depends_on:
            - mongo-auth

    # -------------------------
    # USER DB
    # -------------------------
    mongo-user:
        image: mongo:latest
        container_name: mongo-user
        ports:
            - "27018:27017"
        volumes:
            - mongo_user_data:/data/db

    mongo-express-user:
        image: mongo-express:latest
        container_name: mongo-express-user
        restart: always
        ports:
            - "8082:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo-user
            ME_CONFIG_BASICAUTH: false
        depends_on:
            - mongo-user

volumes:
    mongo_auth_data:
    mongo_user_data:
