services:

  # -------------------------
  # EVENT BUS
  # -------------------------
  nats:
    image: nats:latest
    restart: unless-stopped
    networks:
      - nginx-network


  # -------------------------
  # AUTH SERVICE
  # -------------------------
  ms-auth:
    image: ghcr.io/maximetavares/ms-auth:${IMAGE_TAG}
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - nats

    networks:
      - nginx-network
      - app-network


  # -------------------------
  # GATEWAY
  # -------------------------
  gateway:
    image: ghcr.io/maximetavares/gateway:${IMAGE_TAG}
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - nats

    networks:
      - nginx-network
      - app-network


  # -------------------------
  # FRONT
  # -------------------------
  front:
    image: ghcr.io/maximetavares/front:staging
    restart: unless-stopped

    networks:
      - nginx-network
      - app-network

# -------------------------
# NETWORK
# -------------------------
networks:
  nginx-network:
    external: true

  app-network:
    driver: bridge