services:

  # -------------------------
  # EVENT BUS
  # -------------------------
  staging-nats:
    image: nats:latest
    restart: unless-stopped
    container_name: staging-nats
    networks:
      - nginx-staging

  # -------------------------
  # AUTH SERVICE
  # -------------------------
  staging-ms-auth:
    image: ghcr.io/maximetavares/ms-auth:${IMAGE_TAG}
    restart: unless-stopped
    container_name: staging-ms-auth
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    env_file:
      - .env

    depends_on:
      staging-nats:
        condition: service_started

    networks:
      - nginx-staging

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 10s

  # -------------------------
  # GATEWAY
  # -------------------------
  staging-gateway:
    image: ghcr.io/maximetavares/gateway:${IMAGE_TAG}
    restart: unless-stopped
    container_name: staging-gateway
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    env_file:
      - .env

    depends_on:
      staging-nats:
        condition: service_started

    networks:
      - nginx-staging

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 10s

  # -------------------------
  # FRONT
  # -------------------------
  staging-front:
    image: ghcr.io/maximetavares/front:staging
    restart: unless-stopped
    container_name: staging-front

    networks:
      - nginx-staging

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 3

# -------------------------
# NETWORK
# -------------------------
networks:
  nginx-staging:
    external: true
    name: nginx-staging