services:

  # -------------------------
  # EVENT BUS
  # -------------------------
  nats:
    image: nats:latest
    restart: unless-stopped
    networks:
      - app-network


  # -------------------------
  # MONGO
  # -------------------------
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network


  # -------------------------
  # MS-AUTH
  # -------------------------
  ms-auth:
    image: ghcr.io/maximetavares/ms-auth:${IMAGE_TAG}
    restart: unless-stopped

    environment:
      NATS_URL: nats://nats:4222
      MONGO_URL: mongodb://mongo:27017/auth
      FRONTEND_URL: ${FRONTEND_URL}
      GEOAPIFY_API_KEY: ${GEOAPIFY_API_KEY}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

    depends_on:
      - nats
      - mongo

    networks:
      - app-network


  # -------------------------
  # GATEWAY
  # -------------------------
  gateway:
    image: ghcr.io/maximetavares/gateway:${IMAGE_TAG}
    restart: unless-stopped

    environment:
      NATS_URL: nats://nats:4222
      MONGO_URL: mongodb://mongo:27017/auth
      FRONTEND_URL: ${FRONTEND_URL}
      GEOAPIFY_API_KEY: ${GEOAPIFY_API_KEY}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

    depends_on:
      - nats
      - mongo

    networks:
      - app-network


  # -------------------------
  # FRONT
  # -------------------------
  front:
    image: ghcr.io/maximetavares/front:${IMAGE_TAG}
    restart: unless-stopped

    networks:
      - app-network


# -------------------------
# VOLUMES
# -------------------------
volumes:
  mongo_data:


# -------------------------
# NETWORK
# -------------------------
networks:
  app-network:
    name: app-network