name: Gateway - CI/CD

on:
  push:
    branches: [develop]
    paths:
      - "apps/gateway/**"
      - "packages/contracts/**"

  workflow_dispatch:

  pull_request:
    branches: [develop, main]
    paths:
      - "apps/gateway/**"
      - "packages/contracts/**"

jobs:

  quality:
    if: github.event_name == 'pull_request'

    uses: ./.github/workflows/quality.yml
    with:
      prisma-generate: true
      sonar-source: apps/gateway
      sonar-project-key: ${{ vars.SONAR_GATEWAY_PROJECT_KEY }}
      working-directory: apps/gateway

  build:
    if: github.event_name != 'pull_request'

    uses: ./.github/workflows/docker-build.yml
    with:
      context: .
      image-name: gateway
      file: apps/gateway/Dockerfile

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    needs: build

    uses: ./.github/workflows/deploy.yml
    with:
      compose-directory: /opt/event-app/staging
      compose-service: staging-gateway
      environment: staging
      image-name: gateway
      network: nginx-staging
      run-migrations: true