name: Ms-auth - CI/CD

on:
  push:
    branches: [develop]
    paths:
      - "services/ms-auth/**"
  workflow_dispatch:
  pull_request:
    branches: [develop, main]
    paths:
      - "services/ms-auth/**"


jobs:

  quality:
    if: github.event_name == 'pull_request'

    uses: ./.github/workflows/quality.yml

    with:
      working-directory: services/ms-auth
      sonar-source: services/ms-auth
      sonar-project-key: ${{ vars.SONAR_MS_AUTH_PROJECT_KEY }}

  build:
    if: github.event_name != 'pull_request'

    uses: ./.github/workflows/docker-build.yml

    with:
      context: services/ms-auth
      image-name: ms-auth

  deploy-staging:
    if: github.ref == 'refs/heads/develop'

    needs: build

    uses: ./.github/workflows/deploy.yml

    with:
      compose-directory: /opt/event-app/staging
      compose-service: staging-ms-auth
      image-name: ms-auth
      run-migrations: false


