name: Quality

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

      prisma-generate:
        required: false
        default: false
        type: boolean

      sonar-project-key:
        required: true
        type: string

      sonar-source:
        required: true
        type: string

jobs:
  quality:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        if: inputs.prisma-generate
        run: pnpm prisma generate

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test -- --passWithNoTests

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonar-project-key }}
            -Dsonar.organization=${{ vars.SONAR_ORG }}
            -Dsonar.sources=${{ inputs.sonar-source }}
            -Dsonar.qualitygate.wait=true