name: Quality

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

      prisma-generate:
        required: false
        default: false
        type: boolean

      sonar-project-key:
        required: true
        type: string

      sonar-source:
        required: true
        type: string

jobs:
  quality:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Generate Prisma Client
        if: inputs.prisma-generate
        run: ./node_modules/.bin/prisma generate

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --passWithNoTests

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonar-project-key }}
            -Dsonar.organization=${{ vars.SONAR_ORG }}
            -Dsonar.sources=${{ inputs.sonar-source }}
            -Dsonar.qualitygate.wait=true